Silencing false positive warnings from writev
opendcdiag/opendcdiag pull request #140
Opened 2022-08-12 15:53 UTC by pwlazlyn

GCC 12 incorrectly reports reads outside boundry of an object when we
call writev with IoVec wrapper. We get warning as if it was a single
object and not an array:

    ../opendcdiag/framework/sandstone_iovec.h:39:18: warning: ‘ssize_t writev(int, const iovec*, int)’ reading 48 bytes from a region of size 16 [-Wstringop-overread]
       39 |     return writev(fd, vec, std::size(vec));
          |            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    ../opendcdiag/framework/sandstone_iovec.h:16:8: note: source object ‘{anonymous}::IoVec::<anonymous>’ of size 16
       16 | struct IoVec : iovec
          |        ^~~~~
    In file included from ../opendcdiag/framework/sandstone_p.h:24,
                     from ../opendcdiag/framework/sandstone.cpp:64:
    /usr/include/sys/uio.h:52:16: note: in a call to function ‘ssize_t writev(int, const iovec*, int)’ declared with attribute ‘access (read_only, 2, 3)’
       52 | extern ssize_t writev (int __fd, const struct iovec *__iovec, int __count)
          |                ^~~~~~

This commit provides a simple wrapper that ensures there is enough space
by using size deduction from builtin arrays and silences the warning on
the glibc boundary call.

Signed-off-by: Wlazlyn, Patryk <patryk.wlazlyn@intel.com>

2022-08-12 16:40 UTC, thiagomacieira requested changes
There's a better way that doesn't involve `#pragma`. Let me find it.

2022-08-12 16:44 UTC, thiagomacieira requested changes
See https://codereview.qt-project.org/c/qt/qtbase/+/409083/3..4

The trick was to use a function called `IoVec` that returns `struct iovec`, instead of a type called `IoVec`. 

You can copy the trick because it's copyright Intel (I wrote it). The similarity is not a coincidence.

2022-08-18 10:26 UTC, pwlazlyn commented
> See https://codereview.qt-project.org/c/qt/qtbase/+/409083/3..4

I thought about this, but It requires additional changes because we were using `IoVec` as a type to declare arrays so we could use ctor for nice syntax. I don't think we can omit the wrapping of each array element in `IoVec()` now.

That being said, I don't really care. Both works for me.

2022-08-18 10:49 UTC, pwlazlyn commented
> See https://codereview.qt-project.org/c/qt/qtbase/+/409083/3..4

btw, I think It's use-after-free, unless qt uses some garbage collection internally.
```cpp
static struct iovec IoVec(const char *str)
{
    return IoVec(std::string(str));
}
```

2022-08-22 15:32 UTC, thiagomacieira commented
> > See https://codereview.qt-project.org/c/qt/qtbase/+/409083/3..4
> 
> btw, I think It's use-after-free, unless qt uses some garbage collection internally.

That's why Qt uses:
```c++
static struct iovec IoVec(const char *str)
{
    struct iovec r = {};
    r.iov_base = const_cast<char *>(str);
    r.iov_len = strlen(str);
    return r;
}
```

2022-08-23 08:27 UTC, pwlazlyn commented
> > > See https://codereview.qt-project.org/c/qt/qtbase/+/409083/3..4
> > 
> > 
> > btw, I think It's use-after-free, unless qt uses some garbage collection internally.
> 
> That's why Qt uses:
> 
> ```c++
> static struct iovec IoVec(const char *str)
> {
>     struct iovec r = {};
>     r.iov_base = const_cast<char *>(str);
>     r.iov_len = strlen(str);
>     return r;
> }
> ```

We only take `const char*` and `std::string_view`, so is it ok to merge it as is?

2022-08-23 17:14 UTC, thiagomacieira approved these changes

2022-08-24 08:07 UTC, merged