bats: regex fix to match suffixes in version string
opendcdiag/opendcdiag pull request #148
Opened 2022-09-08 14:02 UTC by dawid-sabat

ie. match name-v123-suffix (1234567890123456789012345678901234567890)

Signed-off-by: dawid-sabat <dawid.sabat@intel.com>

2022-09-08 15:18 UTC, thac0 approved these changes
👍

2022-09-08 20:04 UTC, thiagomacieira requested changes

2022-09-08 20:04 UTC, thiagomacieira commented on bats/sanity-check/20-selftests.bats
> +    test_yaml_regexp "/version" '([a-z-]+-)?(v[0-9.]+(-[a-z]+)? \([0-9a-f]{40}\)|[0-9]+-[0-9]+-g[0-9a-f]+|[0-9a-f]{12}|[0-9a-f]{40})(-.*)?'
I'd allow digits there too, like "-rc7"

2022-09-09 06:48 UTC, dawid-sabat commented on bats/sanity-check/20-selftests.bats
> +    test_yaml_regexp "/version" '([a-z-]+-)?(v[0-9.]+(-[a-z]+)? \([0-9a-f]{40}\)|[0-9]+-[0-9]+-g[0-9a-f]+|[0-9a-f]{12}|[0-9a-f]{40})(-.*)?'
Done

2022-09-09 21:30 UTC, thiagomacieira approved these changes

2022-09-09 21:30 UTC, merged