[RFC] Skip test execution when during IFS wait time
opendcdiag/opendcdiag pull request #207
Opened 2023-04-19 18:46 UTC by AthenasJimenez

2023-04-19 19:12 UTC, AthenasJimenez commented
Something that I'm still unable to do is marking test result as "skip" instead of "pass". Any way that I could do this?

```
- test: ifs
  time-at-start: { elapsed:      0.000, now: !!timestamp '2023-04-19T19:11:37Z' }
  result: pass
  time-at-end:   { elapsed:     25.999, now: !!timestamp '2023-04-19T19:11:37Z' }
  test-runtime: 26.475
  threads:
  - thread: 0
    id: { logical:  0, package: 0, core:  0, thread: 0, family: 6, model: 0x55, stepping: 4, microcode: 0x2006e05, ppin: null }
    messages:
    - { level: warning, text: 'W> Test "intel_ifs_0" cannot be started at the moment, code: 0x600008200 image ID:  0x2 version: 0x172' }
```

2023-04-19 21:27 UTC, thiagomacieira requested changes
Minor things, looking good.

2023-04-19 21:27 UTC, thiagomacieira commented on tests/ifs/ifs.c
> +                        if (compare_error_codes(result, IFS_SW_TIMEOUT) || compare_error_codes(result, IFS_SW_PARTIAL_COMPLETION)) {
You're parsing the string twice, now.

2023-04-19 21:27 UTC, thiagomacieira commented on tests/ifs/sandstone_ifs.h
> +static bool compare_error_codes(char *c_code, unsigned long long expected)
Add `const` to `c_code`

2023-04-19 21:27 UTC, thiagomacieira commented on tests/ifs/ifs.c
> +                        log_warning("Test \"%s\" cannot be started at the moment, code: %s image ID: %s version: %s", ifs_info->sys_dir, result, ifs_info->image_id, ifs_info->image_version);
This can probably be downgraded to `log_info`

2023-04-20 07:03 UTC, markdryan commented
> Something that I'm still unable to do is marking test result as "skip" instead of "pass". Suggestions?
> 
> ```
> - test: ifs
>   time-at-start: { elapsed:      0.000, now: !!timestamp '2023-04-19T19:11:37Z' }
>   result: pass
>   time-at-end:   { elapsed:     25.999, now: !!timestamp '2023-04-19T19:11:37Z' }
>   test-runtime: 26.475
>   threads:
>   - thread: 0
>     id: { logical:  0, package: 0, core:  0, thread: 0, family: 6, model: 0x55, stepping: 4, microcode: 0x2006e05, ppin: null }
>     messages:
>     - { level: warning, text: 'W> Test "intel_ifs_0" cannot be started at the moment, code: 0x600008200 image ID:  0x2 version: 0x172' }
> ```

@AthenasJimenez not sure if this helps, but if every thread returns EXIT_SKIP from its run function the test will skip, even if EXIT_SUCCESS was returned from the init function.

2023-04-24 21:25 UTC, thiagomacieira approved these changes

2023-04-27 16:05 UTC, merged