framework: process enabled tests as arguments
opendcdiag/opendcdiag pull request #364
Opened 2023-08-02 17:00 UTC by mrkz

Previous to this commit, each test enabled needed to be passed with the -e option (multiple times, as tests names are specified).

this commit changes how enabled tests are processed, getting rid of the -e option. Now tests names are passed as arguments.

old command syntax:
 $ opendcdiag -e test1 -e test2 -e test3

after this commit syntax:
 $ opendcdiag test1 test2 test3

2023-08-02 17:17 UTC, mrkz commented
note to self: `selftests` failing due to missing `-e` option used within those test runs

2023-08-02 17:45 UTC, thiagomacieira requested changes
Needs testing in bats/sanity-check - converting some of the tests there to run without `-e` would suffice.

2023-08-02 17:45 UTC, thiagomacieira commented on framework/sandstone.cpp
> -        case 'e':
Please don't remove `'e'`. This will break everyone.

The rest is fine.

2023-08-03 15:16 UTC, busykai commented
I don't think this is a correct change. What about `--disable` option? Why it would behave differently? Also, instead of processing arguments to `-e` this consumes "all the rest of the arguments" as enabled tests which is just wrong. So, no from me unless a good reason for this is provided.

2023-08-03 18:07 UTC, mrkz commented
> What about --disable option? Why it would behave differently? Also, instead of processing arguments to -e this consumes "all the rest of the arguments" as enabled tests which is just wrong. 

I feel it makes sense since there's also a `--test-list-file` option, which specifies enabled tests using a text file. This sounds to me like providing a list of enabled tests is more frequent than a list to disable tests (i.e: there's no `--disable-test-list-file`)

> So, no from me unless a good reason for this is provided.

This came out as a talk I had with @thiagomacieira  about processing the rest of the arguments (having processed all options), so that it could be useful by piping with `xargs` (as an example).

> Generally, this is not a right thing to do, IMO.

I'm not strongly opinionated on this one (again, I just landed an idea from a conversation), so feel free to share more feedback on what would make more sense to you or close it if it wouldn't work for you.

2023-08-04 16:16 UTC, busykai commented
> > So, no from me unless a good reason for this is provided.
> 
> This came out as a talk I had with @thiagomacieira about processing the rest of the arguments (having processed all options), so that it could be useful by piping with `xargs` (as an example).

We have test lists to manage bulky of enabled lists. Giving preference to enabled tests as free positional arguments is not right. `xargs`, by the way, is perfectly capable of prepending `-e` to each item.

> 
> > Generally, this is not a right thing to do, IMO.
> 
> I'm not strongly opinionated on this one (again, I just landed an idea from a conversation), so feel free to share more feedback on what would make more sense to you or close it if it wouldn't work for you.

What we really need is an exclude test file list. People struggle to maintain all the tests they do not want to run at the command line. It is most frequently requested feature and it's really important for us to have as well. So maybe let's sync.

2023-08-14 16:08 UTC, thiagomacieira commented
> We have test lists to manage bulky of enabled lists. Giving preference to enabled tests as free positional arguments is not right. `xargs`, by the way, is perfectly capable of prepending `-e` to each item.

Interesting, I didn't know `-I` could do that.
```
$ (print a; print b; print c) | xargs -I@ echo -e@
-ea
-eb
-ec
```

It's also possible with a shell array (at least with Zsh):
```
$ l=(a b c); echo -e${^l}
-ea -eb -ec
```

But it's much nicer if you don't have to deal with that, which I why I asked for this feature.

> What we really need is an exclude test file list. People struggle to maintain all the tests they do not want to run at the command line. It is most frequently requested feature and it's really important for us to have as well. So maybe let's sync.

I agree, but that's orthogonal. We have the file list parser and we can easily use that to get a list of tests to be disabled.

It might also make sense to extend the syntax of the file to support groups, fatal-skips and, why not, disabling.
```
# comment
-test1
@group1
test2
!test3
```

That means "disable test1" (probably because it would otherwise be enabled by `@group1`), then add the roster of tests in that group, then `test2` and finally `test3` in fatal-skip mode.

Maybe `!` is not the best character to indicate importance, as it's usually used in negations, as in git's exclude and attribute files. Plus, if we use the same syntax as the command-line, we wouldn't want to use `-` for negation either. That leaves still a few options, some of which are not even shell special like `%`.

2023-08-14 16:09 UTC, thiagomacieira approved these changes
Good for me but don't merge until @busykai is also satisfied.

2023-08-15 18:23 UTC, busykai commented
This is a no-go as implemented. To me it's just broken and introduces more weirdness we will have to inevitably deal with. For example, this works:

```bash
opendcdiag -e zstd_aaa -v zlib9
```

so does this:

```bash
opendcdiag zlib1 -e zstd_aaa -v zlib9
```

If we want to salvage the idea (not the implementation), then another approach is needed. We must not modify the behavior of `-e|--enable` instead, we should allow remainder of the option be test specification, so that either:
```
opendcdiag -v zstd_aaa zlib1 zlib9
```
or
```
opendcdiag -v -e zsta_aaa -e zlib1 -e zlib9
```
work. Better yet, I don't recall if it's possible with the standard `getopt_long`, only allow free test arguments after `--`. Additional perk could be that a test name prefixed with `-` would be a request to exclude, i.e.

```bash
opendcdiag -v -- zstd_aaa zlib1 zlib9
opendcdiag -v -e zstd_aaa -- zlib1 zlib9
opendcdiag -v -- -zstd_aaa # run all but zstd_aaa
```
but NOT
```bash
opendcdiag -v zstd_aaa zlib1 zlib9 # missing double hyphen
opendcdiag -v -e zstd_aaa zlib1 # missing double hyphen
opendcdiag  zlib1 -v -e zstd_aaa zlib9 # we must not allow this
```

CC: @mrkz @thiagomacieira

2024-10-17 20:50 UTC, busykai commented
This went stale and the base has/will change significantly. If there's a re-work, it should be a new PR.

2024-10-17 20:50 UTC, closed without merging