FW/Skip: Add new skip category "TestConfigurationSkipCategory"
opendcdiag/opendcdiag pull request #394
Opened 2023-08-23 18:00 UTC by dshivaraintel

This skip can be used when the test doesn't have enough information/configuration that it needs.

After the changes:

```
result: skip
skip-category: TestConfigurationSkipCategory
skip-reason: 'Not enough information for the test'
```

@eamartin96, @pwlazlyn and @jposwiata requested for this category as their DSA test needs it.

2023-08-23 23:08 UTC, eamartin96 approved these changes

2023-08-24 07:54 UTC, jposwiata commented on framework/logging.cpp
> +    case SkipCategory(10):
BTW. Could we "reverse" the checking logic? I mean:
```
switch (SkipCategory(val)) {
    case ResourceIssueSkipReason:
         return "ResourceIssueSkipReason";
    ...
    default:
         // code unreachable
         return "NotPresentSkipCategory";
}
```

2023-08-24 07:56 UTC, jposwiata approved these changes
Looks like solution suitable for our needs. Is there any documentation to add this category, or this is still "in development" stage?

2023-08-24 13:57 UTC, pwlazlyn requested changes
I think `ResourceIssueSkipCategory` is enough to cover our needs.

If the environment was in a configuration that does not allow to execute a test correctly, that's a resource issue - not enough cpus, some runtime feature is not available for the given thread, we cannot allocate memory big enough or with some specific characteristics etc.

2023-08-31 16:59 UTC, dshivaraintel commented
Closing this PR as this category is not necessary.

2023-08-31 16:59 UTC, closed without merging