FW/Random: make the AES engine optional and detected at runtime
opendcdiag/opendcdiag pull request #459
Opened 2023-11-22 21:51 UTC by thiagomacieira

This allows the AES engine to be enabled even if the target compilation options do not include AES. We'll compile the code but only run it if the AESNI instructions are detected at runtime.

Also include a few fixes for the handling of the `-s` option when passed a file. If it weren't at least that big, the error messages the tool printed were misleading:

```
$ echo a > /tmp/seed
$ ./opendcdiag -n1 -s /tmp/seed
read: No such file or directory
```

A case of "Not a typewriter"[1]. Now you get:

[1] https://en.wikipedia.org/wiki/Not_a_typewriter

2023-11-27 23:09 UTC, AthenasJimenez requested changes
Overall, it looks good.

2023-12-02 06:59 UTC, thiagomacieira commented on framework/random.cpp
> +        if (haveAes() && randomdata & 0x80)
Right. I thought it didn't matter because the data is truly random, but it isn't: it can come from a file. Will swap around.

2023-12-02 07:02 UTC, thiagomacieira commented on framework/random.cpp
> +            if (uint8_t type; read_from_seed(type) && (type & 1))
Here I did change the interpretation. Previously, if bit 1 was set, we'd select the AES engine; now we do if bit 1 is set.

Updating.

2023-12-04 23:09 UTC, AthenasJimenez commented on framework/random.cpp
> +        if (haveAes() && randomdata & 0x80)
oh I see, just a way to have 50/50 chance to choose LCG or AES.

2023-12-04 23:16 UTC, AthenasJimenez approved these changes

2023-12-15 15:45 UTC, merged