FW: Implement cpu jump during test execution
opendcdiag/opendcdiag pull request #501
Opened 2024-04-10 15:26 UTC by AthenasJimenez

The goal of this change is allow tests to be executed in multiple cpus during their runtime, always choosing the next available logical cpu.

2025-02-21 20:01 UTC, thiagomacieira requested changes

2025-02-21 20:01 UTC, thiagomacieira commented on framework/sandstone.cpp
> +    tid_t pair_tid = sApp->test_thread_data(pair_thread_num)->tid.load();
`.load(std::memory_order_relaxed)`

2025-02-24 16:52 UTC, AthenasJimenez commented on framework/sandstone_thread.cpp
> +        //auto clear_tid = scopeExit([] { sApp->test_thread_data(thread_num) = 0; }); // TODO: Fix this
There were 2 problems: not capturing `this` for lambda and using `=` instead of `store` for an Atomic value, fixed on new PR #585 

```
../framework/sandstone_thread.cpp: In lambda function:
../framework/sandstone_thread.cpp:93:68: error: 'this' was not captured for this lambda function
   93 |         auto clear_tid = scopeExit([this] { sApp->test_thread_data(thread_num) = 0; }); // TODO: Fix this
      |                                                                    ^~~~~~~~~~
../framework/sandstone_thread.cpp:93:68: error: invalid use of non-static data member 'SandstoneTestThread::thread_num'
In file included from ../framework/sandstone_thread.cpp:6:
../framework/sandstone_thread.h:22:9: note: declared here
   22 |     int thread_num;
      |         ^~~~~~~~~~
ninja: build stopped: subcommand failed.
```

2025-04-29 16:00 UTC, AthenasJimenez commented
Closing in favor of Rescheduling PRs: #602 and #576

2025-04-29 16:00 UTC, closed without merging