FW/Win32: add some more process-summary information
opendcdiag/opendcdiag pull request #512
Opened 2024-05-23 21:16 UTC by thiagomacieira

Available in -vvv output or in case of hang.

2024-06-11 15:35 UTC, AthenasJimenez requested changes

2024-06-11 15:35 UTC, AthenasJimenez commented on framework/sandstone.cpp
> +                us /= 10;   // FILETIME stores tenths of microseconds
Shouldn't this need to be `us *= 10`?

2024-06-13 16:15 UTC, thiagomacieira commented on framework/sandstone.cpp
> +                us /= 10;   // FILETIME stores tenths of microseconds
Yes.

2024-06-13 17:12 UTC, AthenasJimenez approved these changes

2024-06-13 18:38 UTC, merged