FW: reorganize current_max_loop_count assignment
opendcdiag/opendcdiag pull request #562
Opened 2024-10-15 15:59 UTC by mcisowsk

2024-10-15 16:19 UTC, busykai commented
`fracture_loop_count` had the lowest priority, now it has the highest. why is this change?

2024-10-15 16:21 UTC, busykai commented on framework/sandstone.cpp
> +        sApp->shmem->current_max_loop_count = test->fracture_loop_count;
The fallback `else` at the end of this construct does not make sense anymore. However, the question is why we're honoring `fracture_loop_count` over `max_test_loop_count` with this change.

2024-10-16 15:32 UTC, jposwiata commented on framework/sandstone.cpp
>      } else if (test->fracture_loop_count == 0) {
this should be "else" part

2024-10-16 16:19 UTC, busykai commented on framework/sandstone.cpp
> +        sApp->shmem->current_max_loop_count = test->fracture_loop_count;
ok. @mcisowsk please include the reasoning in the commit message (and, optionally, in the PR description).

2024-10-16 16:20 UTC, busykai requested changes
Reorganize the if/else if logic according to the change. Include the reason behind the change in the commit message.

2024-10-17 10:56 UTC, jposwiata approved these changes

2024-10-17 10:57 UTC, jposwiata approved these changes

2024-10-17 17:36 UTC, busykai approved these changes

2024-10-17 17:36 UTC, merged